sudo: false
language: python

python:
  - 2.7.8
  - 2.7.12

perl:
 - 5.16.3

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a


install:
  - conda install --yes -c bioconda samtools=1.3.1
  - conda install --yes -c bioconda bedtools=2.26.0

script:
  - ./INSTALL.sh



