# CMake generated Testfile for 
# Source directory: /panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly
# Build directory: /panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeOnly.LinkInterfaceLoop "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=LinkInterfaceLoop" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
set_tests_properties(CMakeOnly.LinkInterfaceLoop PROPERTIES  TIMEOUT "90")
add_test(CMakeOnly.CheckSymbolExists "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CheckSymbolExists" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXSymbolExists "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CheckCXXSymbolExists" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXCompilerFlag "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CheckCXXCompilerFlag" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckLanguage "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CheckLanguage" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckStructHasMember "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CheckStructHasMember" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdC "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CompilerIdC" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdCXX "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CompilerIdCXX" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdFortran "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=CompilerIdFortran" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.AllFindModules "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=AllFindModules" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.SelectLibraryConfigurations "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=SelectLibraryConfigurations" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.TargetScope "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=TargetScope" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_library "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=find_library" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_path "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=find_path" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.ProjectInclude "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=ProjectInclude" "-DCMAKE_ARGS=-DCMAKE_PROJECT_ProjectInclude_INCLUDE=/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/ProjectInclude/include.cmake" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_2 "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_3 "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_2 "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_3 "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_3 "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=MajorVersionSelection-Qt_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_4 "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/bin/cmake" "-DTEST=MajorVersionSelection-Qt_4" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=4;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "/panfs/biopan01/users/312793/PhaME/ext/opt/CMake-3.6.0/Tests/CMakeOnly/Test.cmake")
