language: c++
compiler:
- clang
- gcc
cache: apt
addons:
  apt:
    packages:
    - libtbb-dev
branches:
  only:
  - master
  - cleaner_parsing
  - batch_parsing
  - no-io
script: make allall
notifications:
  slack:
    secure: tfzT8N1fNV+oSV7tide9WrAj3ifs+LONJ3fCH1tUzexqrx23te4lE0oAj9C1cEMJ4evyRYwHNG8HZoLCOy8EfapqbWm6vgLIlkIBpeZ9E6f2jG6v0YuVDWWpqQC3qdGXCqWtHPjgs3i5OLsLwwQ/LItLoTqpBk2aYv+vGNs2F9g=
